[package]
name = "rusthelloworld"
version = "0.1.0"
authors = ["Rafael Ferrés <rafael.ferres-jum@parceiros-kroton.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
